import {
  createToken,
  ensureSchema,
  getRequestOrigin,
  hashSecret,
  HttpError,
  jsonResponse,
  normalizeEmail,
  sendMagicLinkEmail,
} from '../../_shared/mirofish.js'

function getBearerToken(request) {
  const header = request.headers.get('authorization') || ''
  return header.match(/^Bearer\s+(.+)$/i)?.[1]?.trim() || ''
}

export async function onRequest(context) {
  const { request, env } = context

  if (request.method !== 'POST') {
    return jsonResponse({ message: 'Method not allowed.' }, 405)
  }

  try {
    const expectedToken = String(env.MIROFISH_ADMIN_TOKEN ?? '').trim()
    if (!expectedToken || getBearerToken(request) !== expectedToken) {
      throw new HttpError(401, 'Unauthorized.')
    }
    if (!env.DB) throw new HttpError(503, 'Database not available.')
    await ensureSchema(env)

    const body = await request.json().catch(() => {
      throw new HttpError(400, 'Request body must be valid JSON.')
    })
    const orderId = String(body.orderId ?? '').trim()
    if (!/^[a-f0-9]{32}$/.test(orderId)) throw new HttpError(400, 'Valid order ID is required.')

    const order = await env.DB.prepare(`SELECT * FROM mf_orders WHERE id = ?`).bind(orderId).first()
    if (!order) throw new HttpError(404, 'Order not found.')

    const claimToken = createToken(36)
    const claimHash = await hashSecret(claimToken, env)
    const expiresAt = new Date(Date.now() + 1000 * 60 * 60 * 24 * 90).toISOString()
    const timestamp = new Date().toISOString()

    await env.DB.prepare(
      `UPDATE mf_orders SET claim_token_hash = ?, claim_expires_at = ?, updated_at = ? WHERE id = ?`,
    )
      .bind(claimHash, expiresAt, timestamp, orderId)
      .run()

    const instance = await env.DB.prepare(`SELECT id FROM mf_instances WHERE order_id = ? ORDER BY created_at DESC LIMIT 1`)
      .bind(orderId)
      .first()

    await env.DB.prepare(
      `INSERT INTO mf_instance_claims (id, order_id, instance_id, claim_token_hash, expires_at, created_at) VALUES (?, ?, ?, ?, ?, ?)`,
    )
      .bind(crypto.randomUUID().replace(/-/g, ''), orderId, instance?.id ?? null, claimHash, expiresAt, timestamp)
      .run()

    const consolePath = `/console?claim=${encodeURIComponent(claimToken)}`
    const consoleUrl = `${getRequestOrigin(request, env)}${consolePath}`
    const email = normalizeEmail(body.email || order.customer_email)
    let emailSent = false
    if (email) {
      emailSent = await sendMagicLinkEmail(env, {
        email,
        magicLink: consoleUrl,
        subject: 'Open your MiroFish workspace',
        text: `Open your MiroFish workspace:\n\n${consoleUrl}\n\nThis link can be regenerated by support if needed.`,
        html: `<p>Open your MiroFish workspace:</p><p><a href="${consoleUrl}">Open MiroFish workspace</a></p><p>This link can be regenerated by support if needed.</p>`,
      })
    }

    return jsonResponse({
      message: emailSent ? 'Claim link regenerated and sent.' : 'Claim link regenerated.',
      orderId,
      consolePath,
      consoleUrl,
      emailSent,
    })
  } catch (error) {
    return jsonResponse(
      { message: error instanceof Error ? error.message : 'Could not regenerate claim link.' },
      error instanceof HttpError ? error.statusCode : 500,
    )
  }
}
